Parameters:
  FrontendBucketName:
    Type: String
    Description: Name of the S3 bucket for the static frontend

Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref FrontendBucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucketName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"

Outputs:
  FrontendWebsiteURL:
    Description: URL of the static site
    Value: !Sub "http://${FrontendBucket}.s3-website.${AWS::Region}.amazonaws.com"
    Export:
      Name: !Sub "${AWS::StackName}-FrontendWebsiteURL"
